### ISSUE TITLE
Generator error - fails to generate plugin

### ISSUE THREAD

**Issue by pdewouters** [jazzsequence/generator-hm-plugin#20]
node 8.4.0
yeoman 2.0.0

```
 Client Name Human Made
? Name Attendify API
? Homepage https://hmn.md
? Description Publish posts to Attendify app
? Version 1.0.0-alpha
? Author Human Made
? Author Email hello@hmn.md
? Author URL https://hmn.md
? License GPLv2
? Plugin Slug attendify-api
? Project Namespace HumanMade
? Plugin Namespace AttendifyAPI
? Use Autoloader Basic
events.js:182
      throw er; // Unhandled 'error' event
      ^

ReferenceError: classname is not defined
    at eval (lodash.templateSources[2]:54:11)
    at process (/Users/paul/.nvm/versions/node/v8.4.0/lib/node_modules/generator-hm-plugin/node_modules/mem-fs-editor/actions/copy-tpl.js:11:58)
    at applyProcessingFunc (/Users/paul/.nvm/versions/node/v8.4.0/lib/node_modules/generator-hm-plugin/node_modules/mem-fs-editor/actions/copy.js:12:16)
    at EditionInterface.exports._copySingle (/Users/paul/.nvm/versions/node/v8.4.0/lib/node_modules/generator-hm-plugin/node_modules/mem-fs-editor/actions/copy.js:55:24)
    at EditionInterface.exports.copy (/Users/paul/.nvm/versions/node/v8.4.0/lib/node_modules/generator-hm-plugin/node_modules/mem-fs-editor/actions/copy.js:22:17)
    at EditionInterface.module.exports [as copyTpl] (/Users/paul/.nvm/versions/node/v8.4.0/lib/node_modules/generator-hm-plugin/node_modules/mem-fs-editor/actions/copy-tpl.js:9:8)
    at constructor.php (/Users/paul/.nvm/versions/node/v8.4.0/lib/node_modules/generator-hm-plugin/app/index.js:162:15)
    at /Users/paul/.nvm/versions/node/v8.4.0/lib/node_modules/generator-hm-plugin/node_modules/yeoman-generator/lib/base.js:409:16
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
```

**Comment by jazzsequence** [comment]
this is odd because I literally just created a plugin last week with the generator and it was fine.
I have Node 7.10.0 and Yeoman 1.8.5 but I can't imagine _older_ versions would be a problem...
Let me try upgrading and see if that changes anything.

**Comment by jazzsequence** [comment]
I just upgraded Node/NPM and Yeoman and I can generate plugins fine. I'm guessing it's one of the dependencies in your environment -- the log/error mentions `mem-fs-editor` several times, is the plugin generator installed globally?
